language: python
matrix:
  include:
    - name: "Python 3.7 on Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
        - pip3 install geos
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
# command to install dependencies
install:
  - pip3 install .
# command to run tests
script:
  - python3 -m unittest
